### ISSUE TITLE
variable is unused for ArrayAccess and ArrayObject array assignments.

### ISSUE THREAD

**Issue by pjordaan** [hostnet/PHP_CodeSniffer#12]
I had this one in a unit test, in normal code I don't think you'll see it. I also wonder if you can fix it without writing PHP yourself :)

Example code:
```php
/**
 * @expectedException InvalidTypeException
 **/
public function testException
{
    $item = new MyArrayObjectClass();
    $item[] = 'invalid-type';
}
```

This will tell me that $item is unused, but $item[] = <bla> will internally call __offsetSet which can do other things (like throwing exception)

**Comment by stefanlenselink** [comment]
fixed in new phpcs verison
